# Generated by Django 6.0.5 on 2026-05-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_profile_photo_userprofile_tupper_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealselection',
            name='breakfast_id',
        ),
        migrations.RemoveField(
            model_name='mealselection',
            name='dinner_id',
        ),
        migrations.RemoveField(
            model_name='mealselection',
            name='juice_id',
        ),
        migrations.RemoveField(
            model_name='mealselection',
            name='lunch_id',
        ),
        migrations.AddField(
            model_name='mealselection',
            name='selections',
            field=models.JSONField(default=dict),
        ),
    ]
