# Generated by Django 6.0.5 on 2026-05-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_mealselection_breakfast_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(help_text='ID único para el frontend (ej: b1, l2)', max_length=10, unique=True)),
                ('name_es', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('breakfast', 'Desayuno'), ('snack1', 'Snack Mañana'), ('lunch', 'Almuerzo'), ('snack2', 'Snack Tarde'), ('dinner', 'Cena'), ('juices', 'Zumo Bio-Hacker')], max_length=20)),
                ('kcal', models.IntegerField(default=0)),
                ('protein', models.FloatField(default=0.0, help_text='Gramos de proteína')),
                ('carbs', models.FloatField(default=0.0, help_text='Gramos de carbohidratos')),
                ('fats', models.FloatField(default=0.0, help_text='Gramos de grasas')),
                ('img_path', models.CharField(help_text='Ruta a la imagen (ej: /meals/avena_bowl.png)', max_length=500)),
                ('ingredients', models.JSONField(default=list, help_text='Lista de ingredientes principales')),
                ('recipe', models.TextField(blank=True, help_text='Pasos de la receta')),
                ('prep_mode', models.TextField(blank=True, help_text='Modo de preparación/calentado')),
                ('storage_info', models.TextField(blank=True, help_text='Instrucciones de conservación')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Coste interno', max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio cliente', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
