# Generated by Django 6.0.5 on 2026-05-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mealhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dietary_notes',
            field=models.TextField(blank=True, help_text='Alergias, alimentos no deseados, etc.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
