# Generated by Django 6.0.5 on 2026-05-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_dietary_notes_userprofile_is_vegetarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mealhistory',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealhistory',
            name='issue_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealhistory',
            name='pepper_rating',
            field=models.IntegerField(default=3, help_text='Punto de pimienta (1-5)'),
        ),
        migrations.AddField(
            model_name='mealhistory',
            name='salt_rating',
            field=models.IntegerField(default=3, help_text='Punto de sal (1-5)'),
        ),
        migrations.AlterField(
            model_name='mealhistory',
            name='comment',
            field=models.TextField(blank=True, help_text='Comentario del usuario'),
        ),
    ]
