# Generated by Django 6.0.5 on 2026-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_meal_barcode_mealhistory_is_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='avg_pepper_rating',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='avg_rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='avg_salt_rating',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
