# Generated by Django 6.0.5 on 2026-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_meal_avg_pepper_rating_meal_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='avg_sugar_rating',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='flavor_profile',
            field=models.CharField(choices=[('savory', 'Salado'), ('sweet', 'Dulce')], default='savory', max_length=10),
        ),
        migrations.AddField(
            model_name='mealhistory',
            name='meal_photo',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_photos/'),
        ),
        migrations.AddField(
            model_name='mealhistory',
            name='sugar_rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='mealhistory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealhistory',
            name='pepper_rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='mealhistory',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mealhistory',
            name='salt_rating',
            field=models.IntegerField(default=3),
        ),
    ]
