# Generated by Django 6.0.5 on 2026-05-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_age_userprofile_target_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credits',
            field=models.IntegerField(default=100),
        ),
    ]
