# Generated by Django 6.0.5 on 2026-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealhistory',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
