# Generated by Django 6.0.5 on 2026-05-11 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_mealhistory_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items_count', models.IntegerField(default=1)),
                ('status', models.CharField(default='paid', max_length=20)),
                ('items_data', models.JSONField(help_text='Copia de los platos comprados con sus códigos de barras')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=100)),
                ('last_restock', models.DateTimeField(auto_now=True)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='api.meal')),
            ],
        ),
    ]
